const { Drinks } = require('./index');
const mongoose = require('mongoose');

const mongoURI = process.env.MONGODB_URI || 'mongodb+srv://kyle:1XbajRXflDZiFR2x@mvpcluster.kba0n.mongodb.net/myFirstDatabase?retryWrites=true&w=majority'

try {
  // Connect to the MongoDB cluster
  mongoose.connect (
    mongoURI,
    { useNewUrlParser: true, useUnifiedTopology: true,  useFindAndModify: false, useCreateIndex: true, },
    () => console.log('==================== Mongoose Connected ====================')
  );

} catch (e) {
  console.log("could not connect");
}

const urlBuilder = (drinkName) => {
  return `https://cdnimg.webstaurantstore.com/uploads/blog/2019/4/coffee-drinks_${drinkName}.jpg`;
};

// Coffee Cards Credit to: https://www.webstaurantstore.com/article/397/types-of-coffee-drinks.html

const seedData = [

  { index: 0,
    name: 'Espresso',
    ratio: '1 shot of espresso',
    cup: '2-4 oz. Espresso Cup',
    description: 'The espresso, also known as a short black, is approximately 1 oz. of highly concentrated coffee. Although simple in appearance, it can be difficult to master.',
    image: urlBuilder('Espresso'),
  },
  { index: 1,
    name: 'Double Espresso',
    ratio: '2 shots of espresso',
    cup: 'Demitasse Cup',
    description: 'A double espresso may also be listed as doppio, which is the Italian word for double. This drink is highly concentrated and strong.',
    image: urlBuilder('Double-Espresso'),
  },
  { index: 2,
    name: 'Red Eye',
    ratio: '1 shot of espresso + 6 oz. of drip-brewed coffee',
    cup: '8 oz. Coffee Mug',
    description: 'The red eye\'s purpose is to add a boost of caffeine to your standard cup of coffee.',
    image: urlBuilder('Red-Eye'),
  },
  { index: 3,
    name: 'Black Eye',
    ratio: '2 shots of espresso + 6 oz. of drip-brewed coffee',
    cup: '8-10 oz. Coffee Mug',
    description: 'The black eye is just the doubled version of the red eye and is very high in caffeine.',
    image: urlBuilder('Black-Eye'),
  },
  { index: 4,
    name: 'Americano',
    ratio: '1 shot of espresso + 3 oz. of hot water',
    cup: '5-6 oz. Glass Coffee Mug',
    description: 'Americanos are popular breakfast drinks and thought to have originated during World War II. Soldiers would add water to their coffee to extend their rations farther. The water dilutes the espresso while still maintaining a high level of caffeine.',
    image: urlBuilder('Americano'),
  },
  { index: 5,
    name: 'Long Black',
    ratio: '2 shots of espresso + 3 oz. of hot water',
    cup: '6-8 oz. Glass Coffee Mug',
    description: 'The long black is a similar coffee drink to the americano, but it originated in New Zealand and Australia. It generally has more crema than an americano.',
    image: urlBuilder('Long-Black'),
  },
  { index: 6,
    name: 'Macchiato',
    ratio: '1 shot of espresso + 1 to 2 teaspoons of steamed milk',
    cup: '3 oz. Glass Espresso Cup',
    description: 'The word “macchiato” means mark or stain. This is in reference to the mark that steamed milk leaves on the surface of the espresso as it is dashed into the drink. Flavoring syrups are often added to the drink according to customer preference.',
    image: urlBuilder('Macchiato'),
  },
  { index: 7,
    name: 'Long Macchiato',
    ratio: '2 shots of espresso + 2 to 4 teaspoons of steamed milk',
    cup: '5 oz. Rocks Glass',
    description: 'Often confused with a standard macchiato, the long macchiato is a taller version and will usually be identifiable by its distinct layers of coffee and steamed milk.',
    image: urlBuilder('Macchiato'),
  },
  { index: 8,
    name: 'Cortado',
    ratio: '1 shot of espresso + 1 oz. of warm milk + 1 cm of foam',
    cup: '5 oz. Rocks Glass',
    description: 'The cortado takes the macchiato one step further by evenly balancing the espresso with warm milk in order to reduce the acidity.',
    image: urlBuilder('Cortado'),
  },
  { index: 9,
    name: 'Breve',
    ratio: '1 shot of espresso + 3 oz. of steamed half-and-half + 1 cm of foam',
    cup: '5-7 oz. Low Cup',
    description: 'The breve provides a decadent twist on the average espresso, adding steamed half-and-half to create a rich and creamy texture.',
    image: urlBuilder('Breve'),
  },
  { index: 10,
    name: 'Cappuccino',
    ratio: '1-2 shots of espresso + 2 oz. of steamed milk + 2 oz. of foamed milk + sprinkling of chocolate powder (optional)',
    cup: '6-8 oz. Cappuccino Mug',
    description: 'This creamy coffee drink is usually consumed at breakfast time in Italy and is loved in the United States as well. It is usually associated with indulgence and comfort because of its thick foam layer and additional flavorings that can be added to it.',
    image: urlBuilder('Cappuccino'),
  },
  { index: 11,
    name: 'Flat White',
    ratio: '1 shot of espresso + 4 oz. of steamed milk',
    cup: '6 oz. Glass Tumbler',
    description: 'A flat white also originates from New Zealand and Australia and is very similar to a cappuccino but lacks the foam layer and chocolate powder. To keep the drink creamy rather than frothy, steamed milk from the bottom of the jug is used instead of from the top.',
    image: urlBuilder('Flat-White'),
  },
  { index: 12,
    name: 'Cafe Latte',
    ratio: '1 shot of espresso + 8-10 oz. of steamed milk + 1 cm of foam',
    cup: '14 oz. Mixing Glass',
    description: 'Cafe lattes are considered an introductory coffee drink since the acidity and bitterness of coffee is cut by the amount of milk in the beverage. Flavoring syrups are often added to the latte for those who enjoy sweeter drinks.',
    image: urlBuilder('caffe-latte'),
  },
  { index: 13,
    name: 'Mocha',
    ratio: '1 shot of espresso + 1-2 oz. of chocolate syrup/powder + 1-3 oz. of steamed milk + 2-3 cm of foam or whipped cream',
    cup: '6-8 oz. Irish Coffee Mug',
    description: 'The mocha is considered a coffee and hot chocolate hybrid. The chocolate powder or syrup gives it a rich and creamy flavor and cuts the acidity of the espresso.',
    image: urlBuilder('Mocha'),
  },
  { index: 14,
    name: 'Vienna',
    ratio: '1-2 shots of espresso + 2 oz. of whipped cream',
    cup: '4-5 oz. Espresso Mug',
    description: 'There are a few variations on the Vienna, but one of the most common is made with two ingredients: espresso and whipped cream. The whipped cream takes the place of milk and sugar to provide a creamy texture.',
    image: urlBuilder('Vienna'),
  },
  { index: 15,
    name: 'Affogato',
    ratio: '1-2 shots of espresso + 1 scoop of vanilla ice cream',
    cup: '5-7 oz. Dessert Dish',
    description: 'Affogatos are more for a dessert coffee than a drink you would find at a cafe, but they can add a fun twist to your menu. They are made by pouring a shot of espresso over a scoop of vanilla ice cream to create a sweet after-meal treat.',
    image: urlBuilder('Affogato'),
  },
  { index: 16,
    name: 'Cafe au Lait',
    ratio: '5 oz. French press coffee + 5 oz. scalded milk',
    cup: '12 oz. Coffee Mug',
    description: 'The cafe au lait is typically made with French press coffee instead of an espresso shot to bring out the different flavors in the coffee. It is then paired with scalded milk instead of steamed milk and poured at a 50/50 ratio.',
    image: urlBuilder('Cafe-au-Lait'),
  },
  { index: 17,
    name: 'Iced Coffee',
    ratio: '2 oz. drip coffee or espresso + 4 oz. of ice + 4-6 oz of milk or water + flavoring syrup to taste',
    cup: '14 oz. Mixing Glass',
    description: 'Iced coffees become very popular in the summertime in the United States. The recipes do have some variance, with some locations choosing to interchange milk with water in the recipe. Often, different flavoring syrups will be added per the preference of the customer.',
    image: urlBuilder('Iced-Coffee'),
  },
];

  const seed = () => {
    Drinks.create(seedData)
  };

  seed();
